In [8]:
import math as m
print(m.cos(50))

0.9649660284921133


In [9]:
import numpy as np
arr = np.array([1,3,4,5,6,7])
print(arr)

[1 3 4 5 6 7]


In [10]:
import time
print(arr[2])
print (arr*2)
l1 =list(range(1,1000))
a=np.array(l1)


4
[ 2  6  8 10 12 14]


In [14]:
import time as t

# list time
start = t.time()
new_l = [x * 2 for x in l1]
end = t.time()
time_list = end - start
print("List time is", time_list)

start1 = t.time()
new_a = a * 2
end1 = t.time()
time_a = end1 - start1
print("Array time is", time_a)

List time is 0.00014090538024902344
Array time is 0.00017905235290527344


In [16]:
arr = np.array([[1,3,4],[5,2,9],[12,4,78],[0,-1,5]])
print(arr)

[[ 1  3  4]
 [ 5  2  9]
 [12  4 78]
 [ 0 -1  5]]


In [ ]:
print(arr[0:2,0:2])
print()

[[1 3]
 [5 2]]


In [ ]:
print(np.linalg.eig(arr))
